language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
    code_climate:
        repo_token: d15333ee3ab1183432a7ee1b6075719ac18be318af6a62c3bbc68ea290e4fe4c

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info